### ISSUE TITLE
xds relay fetches incorrect eds resources

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/xds-relay#147]
Snapshot of versioninfo on upstream envoymanager and xds relay

```
```

**Comment by jyotimahapatra** [comment]
Found the reason for this. The aggregator rule in our private repo specific to Lyft had a bug due to which eds requests were cached on service name. So when svcA asked for eds, the last eds won and overwrote eds for all previous services

**Comment by jyotimahapatra** [comment]
After adding rules to add resource name for eds, the cache is happy now.
```
  - rules:
    - match:
        request_type_match:
          types:
            - "type.googleapis.com/envoy.api.v2.RouteConfiguration"
            - "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
            - "type.googleapis.com/envoy.api.v2.ClusterLoadAssignment"
            - "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment"
      result:
        resource_names_fragment:
          element: 0
          action: { exact: true }
```
